version: '3.9'

services:
  recomendation-backend:
    build:
      context: ..
      dockerfile: ./app/backend/Dockerfile
    container_name: recomendation-backend
    ports:
      - "${API_PORT}:8000"
    command: "uvicorn --factory api.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ../app/backend/:/app/
    networks:
      - recomendation

  recomendation-frontend:
    build:
      context: ..
      dockerfile: ./app/frontend/Dockerfile
    container_name: recomendation-frontend
    ports:
      - "${FRONTEND_PORT}:8501"
    command: "streamlit run app.py --server.port=8501 --server.address=0.0.0.0"
    env_file:
      - ../.env
    volumes:
      - ../app/frontend/:/app/
    networks:
      - recomendation
    environment:
      - API_URL=http://fastapi:8000

networks:
  recomendation:
    driver: bridge